#!/usr/bin/env bash

# Arrêt immédiat en cas d'erreur
set -e

echo "[*] Mise à jour du système..."
sudo apt update && sudo apt upgrade -y

echo "[*] Installation des outils d'audit..."
sudo apt install -y \
  nmap \
  tcpdump \
  tshark \
  arp-scan \
  whois \
  curl \
  wget \
  curl \
  nikto \
  git \

echo "[+] Installation terminée !"
